#! /bin/sh

# Refresh Wallpaper
# while feh --randomize --bg-fill /home/flr/res/images/fav
# do
#     sleep 600
# done &

while feh --randomize --bg-fill /home/flr/res/images/fav
do
    sleep 600
done &

# keyboard layout
# KBID=$(xinput list | rg 'AT Translated Set 2 keyboard' | sed 's/^.*\tid=\(.*\)\t.*/\1/')
# {
#     echo "setxkbmap -device \"$KBID\" -model pc105 -layout us -variant norman -option ctrl:swapcaps"
#     setxkbmap -device "$KBID" -model pc105 -layout us -variant norman -option ctrl:swapcaps
# } > ~/.dwm/log

# Autostart
# /usr/lib64/libexec/polkit-kde-authentication-agent-1 &
picom -CGb --daemon
fcitx5 -d
slstatus &
# flameshot &
# pasystray &
# copyq &
# (conky | while read LINE; do xsetroot -name "$LINE"; done) &
